name: "build"

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false

    name: "build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download prerequisites
        run: sudo apt-get install cmake
        
      - name: CMake configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --parallel